#!/bin/sh

set -ex

readlink() {
  (
    cd $(dirname $1)
    echo $PWD/$(basename $1)
  )
}

# Place keys and certificates here
depot_path=$(readlink ./test-certs)
mkdir -p ${depot_path}

# Install certstrap
go get -v github.com/square/certstrap

# CA to distribute to syslog certs
certstrap --depot-path ${depot_path} init --passphrase '' --common-name syslogCA
mv -f ${depot_path}/syslogCA.crt ${depot_path}/syslog-ca.crt
mv -f ${depot_path}/syslogCA.key ${depot_path}/syslog-ca.key
mv -f ${depot_path}/syslogCA.crl ${depot_path}/syslog-ca.crl

# syslog certificate
certstrap --depot-path ${depot_path} request-cert --passphrase '' --common-name syslog
certstrap --depot-path ${depot_path} sign syslog --CA syslog-ca
